---
# Ansible playbook, install nginx on ubuntu.
# Change local to hostgroup set in inventory file.
- hosts: local
 connection: local
 become: yes
 become_user: root
 vars:
   - docroot: /var/www/blackwolf.com/public

 tasks:
 - name: Add Nginx Repository
   apt_repository:
      repo: ppa:nginx/stable
      state: presente
   register: ppastable

 - name: Install Nginx
   apt: 
      name: nginx
      state: installed
      update_cache: true
   when: ppastable|success
   notify:
      - Start Nginx

 - name: Create Web Root
   file:
    path: '{{ docroot }}'
    mode: 775
    state: directory
    owner: www-data
    group: www-data
   notify:
    - Reload Nginx
 handlers:
    - name: Start Nginx
        service:
            name: nginx
            state: started
			
    - name: Reload Nginx
        service:
            name: nginx
            state: reloaded